<?php
//ARRAY CRIADO AUTOMATICAMENTE, CONTENDO AS VARIAVEIS ENVIADAS POR MÉTOSDO GET
print_r($_GET);

//ARRAY CRIADO AUTOMATOMATICAMENTE, CONTENDO AS VARIAVEIS ENVIADAS POR MÉTODOS POST
print_r($_POST);

//FAÇA COM QUE A PÁGINA EXIBIDA os valorwes informados no formulário 

//NÃO ESQUEÇA DE ACRESCENTAR CABECALHO E RODAPÉ EM SUA PÁGINA